#! /bin/bash
# Copyright (c) 2013 HandBand Chile
# All rights reserved.
#
# Author: Juan Canales C.
#
# Please send feedback to jcanales@handband.cl
#
# /etc/init.d/handbandd
#
### BEGIN INIT INFO
# Provides: handbandd
# Required-Start: 
# Should-Start: 
# Required-Stop: 
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Test daemon process
# Description:    Runs up the test daemon process
### END INIT INFO

# Activate the python virtual environment
    . /path_to_virtualenv/activate

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    python /usr/share/handbandd/handbandd.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /usr/share/handbandd/handbandd.py stop
    ;;
  restart)
    echo "Restarting server"
    python /usr/share/handbandd/handbandd.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/handbandd {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
